"""
Mode Selector - Sprint 9 Hybrid Swarm Engine

Selects the optimal collaboration mode using:
1. TaskAnalysis (complexity, domains)
2. DyLAN importance scores (AgentPool)
3. Mode characteristics matching
4. Historical performance

Works with AgentPool to provide data-driven mode selection.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from .agent_metrics import AgentPool, AgentProfile
from .collaboration_modes import CollaborationMode, ModeCharacteristics, get_mode_characteristics
from .task_analyzer import TaskAnalysis

# V7.6 Phase 10b: Memory-Augmented Mode Selection (lazy import)
_SUCCESS_MEMORY_AVAILABLE = False
try:
    from ..memory.success_memory import SuccessMemory

    _SUCCESS_MEMORY_AVAILABLE = True
except ImportError:
    SuccessMemory = None

# V7.6 Phase 13d: AutoMemory Integration (lazy import)
_AUTO_MEMORY_AVAILABLE = False
try:
    from ..memory.auto_memory import AutoMemory, get_auto_memory

    _AUTO_MEMORY_AVAILABLE = True
except ImportError:
    AutoMemory = None
    get_auto_memory = None

# V11.2 MEMORIA: Memory Coordinator (lazy import)
_COORDINATOR_AVAILABLE = False
try:
    from ..memory.coordinator import MemoryCoordinator, UnifiedRecommendation

    _COORDINATOR_AVAILABLE = True
except ImportError:
    MemoryCoordinator = None
    UnifiedRecommendation = None

import logging  # noqa: E402  # after optional dependency blocks

_logger = logging.getLogger(__name__)


@dataclass
class AgentAssignment:
    """Assignment of an agent to a role in a collaboration mode"""

    agent_id: str
    role: str  # "lead", "support", "red", "blue", "equal", "specialist"
    subtask: str | None = None
    confidence: float = 0.5


@dataclass
class ModeProposal:
    """
    Proposal for a collaboration mode.

    Generated by ModeSelector, may be modified by negotiation.
    """

    mode: CollaborationMode
    confidence: float  # 0.0-1.0
    agent_assignments: list[AgentAssignment]
    reasoning: str
    alternatives: list[tuple[CollaborationMode, float]] = field(default_factory=list)
    timestamp: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> dict:
        return {
            "mode": self.mode.value,
            "confidence": round(self.confidence, 3),
            "agent_assignments": [
                {"agent_id": a.agent_id, "role": a.role, "subtask": a.subtask, "confidence": round(a.confidence, 3)}
                for a in self.agent_assignments
            ],
            "reasoning": self.reasoning,
            "alternatives": [{"mode": m.value, "score": round(s, 3)} for m, s in self.alternatives[:3]],
            "timestamp": self.timestamp.isoformat(),
        }


class ModeSelector:
    """
    Selects optimal collaboration mode using DyLAN scoring.

    Combines task analysis with agent performance history
    to recommend the best collaboration mode.

    V7.6 Phase 10b: Supports memory-augmented selection using
    SuccessMemory to boost modes that worked for similar tasks.
    """

    # V7.6 Phase 10b: Memory boost constants (SuccessMemory - semantic similarity)
    MEMORY_BOOST_HIGH = 0.25  # High similarity (>0.5)
    MEMORY_BOOST_MEDIUM = 0.15  # Medium similarity (>0.3)
    MEMORY_BOOST_LOW = 0.08  # Low similarity (>0.2)
    MEMORY_MIN_SIMILARITY = 0.2  # Minimum similarity to apply boost

    # V7.6 Phase 10d: Session-aware scoring weights
    DYLAN_WEIGHT = 0.7  # DyLAN importance weight (70%)
    SESSION_WEIGHT = 0.3  # Session success rate weight (30%)

    # V7.6 Phase 13d: AutoMemory gradient confidence constants
    # AutoMemory uses task_type lookup (not semantic similarity)
    AUTO_MEMORY_BOOST_VERY_HIGH = 0.30  # Confidence >= 0.8
    AUTO_MEMORY_BOOST_HIGH = 0.25  # Confidence >= 0.7
    AUTO_MEMORY_BOOST_LOW = 0.10  # Confidence >= 0.5
    AUTO_MEMORY_MIN_CONFIDENCE = 0.5  # Below this, ignore AutoMemory
    AUTO_MEMORY_LEAD_BONUS = 0.20  # Bonus for suggested lead (confidence > 0.7)

    def __init__(
        self,
        agent_pool: AgentPool | None = None,
        history_weight: float = 0.3,
        success_memory: Optional["SuccessMemory"] = None,
        auto_memory: Optional["AutoMemory"] = None,
    ):
        """
        Initialize ModeSelector.

        Args:
            agent_pool: AgentPool with performance history
            history_weight: Weight given to historical performance (0-1)
            success_memory: V7.6 Phase 10b - SuccessMemory for memory-augmented selection
            auto_memory: V7.6 Phase 13d - AutoMemory for task_type-based mode/lead suggestions
        """
        self.agent_pool = agent_pool
        self.history_weight = history_weight
        self.success_memory = success_memory
        self.selection_history: list[dict] = []

        # V7.6 Phase 10b: Track memory-influenced selections
        self._last_memory_match: dict | None = None

        # V7.6 Phase 13d: AutoMemory integration (lazy singleton fallback)
        if auto_memory is not None:
            self.auto_memory = auto_memory
        elif _AUTO_MEMORY_AVAILABLE and get_auto_memory is not None:
            try:
                self.auto_memory = get_auto_memory()
            except Exception as e:
                _logger.warning(f"Failed to get AutoMemory singleton: {e}")
                self.auto_memory = None
        else:
            self.auto_memory = None

        # V7.6 Phase 13d: Track auto-memory suggestions
        self._last_auto_memory_suggestion: dict | None = None

        # V11.2 MEMORIA: Unified Memory Coordinator
        self.memory_coordinator: MemoryCoordinator | None = None
        if _COORDINATOR_AVAILABLE and MemoryCoordinator is not None and (self.success_memory or self.auto_memory):
            try:
                self.memory_coordinator = MemoryCoordinator(
                    success_memory=self.success_memory, auto_memory=self.auto_memory
                )
                _logger.debug("V11.2 MEMORIA: MemoryCoordinator initialized")
            except Exception as e:
                _logger.warning(f"Failed to initialize MemoryCoordinator: {e}")
                self.memory_coordinator = None

        # V11.2 MEMORIA: Track unified recommendations
        self._last_unified_recommendation: dict | None = None

    def select_mode(
        self, task_analysis: TaskAnalysis, available_agents: list[AgentProfile] | None = None
    ) -> ModeProposal:
        """
        Select optimal collaboration mode for a task.

        V7.6 Phase 10b: Consults SuccessMemory to boost modes that
        worked for similar tasks.

        Args:
            task_analysis: Analysis of the task
            available_agents: Override agents (uses pool if None)

        Returns:
            ModeProposal with recommended mode and assignments
        """
        # Reset memory match trackers
        self._last_memory_match = None
        self._last_auto_memory_suggestion = None

        # Get agents
        if available_agents is None and self.agent_pool:
            available_agents = self.agent_pool.get_active_agents()

        if not available_agents:
            # Fallback: create default profiles
            available_agents = self._create_default_agents()

        # Score all modes
        mode_scores: dict[CollaborationMode, float] = {}
        for mode in CollaborationMode:
            score = self._score_mode(mode, task_analysis, available_agents)
            mode_scores[mode] = score

        # V11.2 MEMORIA: Use unified coordinator if available
        unified_info = None
        unified_lead = None
        memory_boost_mode = None
        memory_boost_info = None
        auto_memory_info = None
        auto_memory_lead = None

        if self.memory_coordinator:
            # V11.2 MEMORIA: Unified memory boost (replaces separate methods)
            boosted_mode, unified_lead, unified_info = self._apply_unified_memory_boost(task_analysis, mode_scores)
            if boosted_mode:
                memory_boost_mode = next((m for m in CollaborationMode if m.value == boosted_mode), None)
                memory_boost_info = unified_info  # Reuse for reasoning
        else:
            # V7.6 Phase 10b: Legacy - Memory-Augmented Selection (SuccessMemory)
            if self.success_memory:
                memory_boost_mode, memory_boost_info = self._apply_memory_boost(task_analysis, mode_scores)

            # V7.6 Phase 13d: Legacy - AutoMemory Integration
            if self.auto_memory:
                auto_memory_info, auto_memory_lead = self._apply_auto_memory_boost(task_analysis, mode_scores)

        # Combine leads (unified takes precedence)
        effective_lead = unified_lead or auto_memory_lead

        # Select best mode
        best_mode = max(mode_scores, key=mode_scores.get)
        best_score = mode_scores[best_mode]

        # Generate alternatives (sorted by score)
        sorted_modes = sorted(mode_scores.items(), key=lambda x: x[1], reverse=True)
        alternatives = [(m, s) for m, s in sorted_modes if m != best_mode]

        # Assign agents (V11.2 MEMORIA: pass effective_lead for lead bonus)
        assignments = self._assign_agents(best_mode, task_analysis, available_agents, effective_lead)

        # Generate reasoning (V7.6: include memory influence)
        reasoning = self._generate_reasoning(best_mode, task_analysis, mode_scores, memory_boost_info, auto_memory_info)

        proposal = ModeProposal(
            mode=best_mode,
            confidence=best_score,
            agent_assignments=assignments,
            reasoning=reasoning,
            alternatives=alternatives,
        )

        # Record selection
        self._record_selection(task_analysis, proposal)

        return proposal

    # V12.4: Task-adaptive decision protocol bias (arxiv:2502.19130, ACL 2025)
    # REASONING domains benefit from independent voting (PARALLEL): +13.2%
    # KNOWLEDGE domains benefit from consensus (PING_PONG): +2.8%
    DOMAIN_PROTOCOL_BIAS: dict[str, dict[CollaborationMode, float]] = {
        # Reasoning-heavy: independent work + voting -> PARALLEL
        "coding": {CollaborationMode.PARALLEL: 0.08, CollaborationMode.LEAD_SUPPORT: 0.03},
        "debugging": {CollaborationMode.PARALLEL: 0.08, CollaborationMode.RED_BLUE: 0.04},
        "analysis": {CollaborationMode.PARALLEL: 0.06, CollaborationMode.LEAD_SUPPORT: 0.03},
        "architecture": {CollaborationMode.PARALLEL: 0.06, CollaborationMode.RED_BLUE: 0.04},
        "testing": {CollaborationMode.PARALLEL: 0.06},
        # Knowledge-heavy: consensus building -> PING_PONG
        "research": {CollaborationMode.PING_PONG: 0.06, CollaborationMode.SEQUENTIAL: 0.03},
        "documentation": {CollaborationMode.PING_PONG: 0.04, CollaborationMode.SEQUENTIAL: 0.03},
        "web_interaction": {CollaborationMode.PARALLEL: 0.05, CollaborationMode.PING_PONG: 0.03},
        # Creative: iterative refinement -> PING_PONG
        "creative": {CollaborationMode.PING_PONG: 0.08, CollaborationMode.LEAD_SUPPORT: 0.03},
        # Security: adversarial review -> RED_BLUE
        "security": {CollaborationMode.RED_BLUE: 0.10, CollaborationMode.LEAD_SUPPORT: 0.03},
    }

    def _score_mode(self, mode: CollaborationMode, analysis: TaskAnalysis, agents: list[AgentProfile]) -> float:
        """
        Score a mode for the given task and agents.

        Combines:
        - Complexity fit (30%)
        - Domain fit (25%)
        - Agent importance scores / DyLAN (25%)
        - Requirements fit (20%)
        - V12.4: Task-adaptive domain-protocol bias (post-hoc adjustment)
        """
        char = get_mode_characteristics(mode)
        score = 0.0

        # 1. Complexity fit (30%)
        complexity_fit = self._score_complexity_fit(char, analysis)
        score += complexity_fit * 0.30

        # 2. Domain fit (25%)
        domain_fit = self._score_domain_fit(char, analysis, agents)
        score += domain_fit * 0.25

        # 3. Agent importance scores - DyLAN (25%)
        dylan_fit = self._score_dylan_fit(mode, analysis, agents)
        score += dylan_fit * 0.25

        # 4. Requirements fit (20%)
        requirements_fit = self._score_requirements_fit(char, analysis)
        score += requirements_fit * 0.20

        # 5. V12.4: Task-adaptive domain-protocol bias (arxiv:2502.19130)
        # Applies research-backed preference: REASONING->voting, KNOWLEDGE->consensus
        domain_key = analysis.primary_domain.value.lower()
        bias_map = self.DOMAIN_PROTOCOL_BIAS.get(domain_key, {})
        score += bias_map.get(mode, 0.0)

        return min(1.0, score)

    def _score_complexity_fit(self, char: ModeCharacteristics, analysis: TaskAnalysis) -> float:
        """Score how well mode complexity matches task"""
        task_complexity_normalized = analysis.complexity.value / 5.0
        diff = abs(char.complexity_affinity - task_complexity_normalized)
        return 1.0 - diff

    def _score_domain_fit(self, char: ModeCharacteristics, analysis: TaskAnalysis, agents: list[AgentProfile]) -> float:
        """
        Score how well agent strengths match task domains.

        V7.5 Phase 5b: Agent-agnostic scoring based on capabilities
        and DyLAN scores, not hardcoded agent names.
        """
        if not agents:
            return 0.5  # Neutral if no agents

        primary_domain = analysis.primary_domain.value.lower()
        score = 0.0

        # Score based on how well available agents match the domain
        for agent in agents:
            capabilities_lower = [c.lower() for c in agent.capabilities]

            # Direct capability match
            if primary_domain in capabilities_lower:
                score += 0.4
            # Substring match (e.g., "coding" in "python_coding")
            elif any(primary_domain in cap for cap in capabilities_lower):
                score += 0.25

            # DyLAN importance for this domain
            dylan_score = agent.get_task_importance(primary_domain)
            score += dylan_score * 0.2

        # Normalize by agent count (max ~0.6 per agent contribution)
        score = score / max(len(agents), 1)

        # Legacy compatibility: check mode strength fits (still useful for mode characteristics)
        if hasattr(char, "gemini_strength_fit") and primary_domain in char.gemini_strength_fit:
            score += 0.1
        if hasattr(char, "claude_strength_fit") and primary_domain in char.claude_strength_fit:
            score += 0.1

        return min(1.0, score)

    def _score_dylan_fit(self, mode: CollaborationMode, analysis: TaskAnalysis, agents: list[AgentProfile]) -> float:
        """
        Score using DyLAN importance scores from agent history.

        V7.6 Phase 10d: Now uses session-aware scoring when SuccessMemory
        is available, combining DyLAN scores with session success rates.
        """
        if not agents:
            return 0.5

        primary_domain = analysis.primary_domain.value
        scores = []

        for agent in agents:
            # V7.6 Phase 10d: Use session-aware score if pool supports it
            if self.agent_pool and self.success_memory:
                score = self.agent_pool.get_session_aware_score(
                    agent_id=agent.agent_id,
                    task_type=primary_domain,
                    success_memory=self.success_memory,
                    dylan_weight=self.DYLAN_WEIGHT,
                )
            else:
                # Fallback to pure DyLAN
                score = agent.get_task_importance(primary_domain)

            scores.append(score)

        if not scores:
            return 0.5

        # For modes that benefit from specialist, reward high variance
        # For modes that need collaboration, reward balanced scores
        avg_score = sum(scores) / len(scores)

        if mode == CollaborationMode.SPECIALIST:
            # Reward when one agent clearly better
            variance = sum((s - avg_score) ** 2 for s in scores) / len(scores)
            return min(1.0, 0.5 + variance)
        else:
            # Reward balanced scores for collaborative modes
            variance = sum((s - avg_score) ** 2 for s in scores) / len(scores)
            return max(0.0, 1.0 - variance)

    def _score_requirements_fit(self, char: ModeCharacteristics, analysis: TaskAnalysis) -> float:
        """Score based on task requirements"""
        score = 0.5  # Base score

        # Web requirement -> prefer parallel (can search while coding)
        if analysis.requires_web and char.parallelism_benefit > 0.5:
            score += 0.2

        # Deep reasoning -> prefer ping-pong or lead-support
        if analysis.requires_deep_reasoning and char.mode in [
            CollaborationMode.PING_PONG,
            CollaborationMode.LEAD_SUPPORT,
        ]:
            score += 0.2

        # Iteration -> prefer ping-pong
        if analysis.requires_iteration and char.mode == CollaborationMode.PING_PONG:
            score += 0.3

        # Security -> require RED_BLUE
        if analysis.needs_adversarial_mode:
            if char.adversarial:
                score += 0.5
            else:
                score -= 0.3

        return max(0.0, min(1.0, score))

    def _assign_agents(
        self,
        mode: CollaborationMode,
        analysis: TaskAnalysis,
        agents: list[AgentProfile],
        auto_memory_lead: str | None = None,
    ) -> list[AgentAssignment]:
        """
        Assign agents to roles based on mode and task.

        V7.5 Phase 5b: Agent-agnostic assignment using capability-based
        selection. Agents are ranked by DyLAN scores and capabilities,
        not by hardcoded names (Gemini/Claude).

        V7.6 Phase 13d: If auto_memory_lead is provided (confidence > 0.7),
        apply +0.20 bonus to the suggested lead agent.
        """
        if not agents:
            return []

        primary_domain = analysis.primary_domain.value

        # V7.5 Phase 5b: Get ranked agents by capability for this domain
        # V7.6 Phase 10d: Now uses session-aware scoring when available
        if self.agent_pool:
            # Use session-aware ranking if success_memory available
            if self.success_memory:
                # Rank by hybrid score (DyLAN + session success)
                ranked_agents = sorted(
                    agents,
                    key=lambda a: self.agent_pool.get_session_aware_score(
                        agent_id=a.agent_id,
                        task_type=primary_domain,
                        success_memory=self.success_memory,
                        dylan_weight=self.DYLAN_WEIGHT,
                    ),
                    reverse=True,
                )
            else:
                # Fallback to capability-based selection
                ranked_agents = self.agent_pool.select_agents_by_capability(domain=primary_domain, count=len(agents))
        else:
            # Fallback: rank by DyLAN importance for the domain
            ranked_agents = sorted(agents, key=lambda a: a.get_task_importance(primary_domain), reverse=True)

        # V7.6 Phase 13d: Apply AutoMemory lead bonus (+0.20)
        # If AutoMemory suggests a lead with high confidence (>0.7),
        # boost that agent's ranking by promoting them to the front
        if auto_memory_lead and ranked_agents:
            suggested_lead_lower = auto_memory_lead.lower()
            for i, agent in enumerate(ranked_agents):
                agent_id_lower = agent.agent_id.lower()
                # Match by agent_id or provider name (e.g., "gemini", "claude")
                if suggested_lead_lower in agent_id_lower or agent_id_lower.startswith(suggested_lead_lower):
                    if i > 0:
                        # Move suggested lead to front (apply bonus effect)
                        boosted_agent = ranked_agents.pop(i)
                        ranked_agents.insert(0, boosted_agent)
                        _logger.debug(f"AutoMemory lead bonus: promoted {agent.agent_id} from position {i} to 0")
                    break

        # Need at least 2 agents for most modes
        if len(ranked_agents) < 2 and mode not in [CollaborationMode.SPECIALIST]:
            # Try to use what we have
            if ranked_agents:
                return [AgentAssignment(agent_id=ranked_agents[0].agent_id, role="specialist", confidence=0.6)]
            return []

        assignments = []
        assigned_ids = set()

        def get_next_best(exclude: set) -> AgentProfile | None:
            """Get next best agent not already assigned."""
            for agent in ranked_agents:
                if agent.agent_id not in exclude:
                    return agent
            return None

        if mode == CollaborationMode.PARALLEL:
            # Top 2 agents work in parallel
            for idx in range(min(2, len(ranked_agents))):
                agent = ranked_agents[idx]
                subtask = "research_and_web" if idx == 0 and analysis.requires_web else f"subtask_{idx + 1}"
                assignments.append(
                    AgentAssignment(
                        agent_id=agent.agent_id,
                        role="equal",
                        subtask=subtask,
                        confidence=0.8 - (idx * 0.1),  # Slightly lower for second agent
                    )
                )
                assigned_ids.add(agent.agent_id)

        elif mode == CollaborationMode.SEQUENTIAL:
            # Best agent first, second-best agent second
            first = ranked_agents[0] if ranked_agents else None
            second = get_next_best({first.agent_id} if first else set())

            if first:
                assignments.append(AgentAssignment(agent_id=first.agent_id, role="first", confidence=0.8))
            if second:
                assignments.append(AgentAssignment(agent_id=second.agent_id, role="second", confidence=0.7))

        elif mode == CollaborationMode.LEAD_SUPPORT:
            # Best agent is lead, second-best is support
            lead = ranked_agents[0] if ranked_agents else None
            support = get_next_best({lead.agent_id} if lead else set())

            if lead:
                # Calculate confidence based on agent's domain fit
                lead_importance = lead.get_task_importance(primary_domain)
                assignments.append(
                    AgentAssignment(
                        agent_id=lead.agent_id, role="lead", confidence=min(0.95, 0.6 + lead_importance * 0.35)
                    )
                )
            if support:
                assignments.append(AgentAssignment(agent_id=support.agent_id, role="support", confidence=0.6))

        elif mode == CollaborationMode.PING_PONG:
            # Top 2 agents alternate
            for idx in range(min(2, len(ranked_agents))):
                agent = ranked_agents[idx]
                assignments.append(AgentAssignment(agent_id=agent.agent_id, role="equal", confidence=0.7))

        elif mode == CollaborationMode.SPECIALIST:
            # Single best agent for the domain
            specialist = ranked_agents[0] if ranked_agents else None
            if specialist:
                importance = specialist.get_task_importance(primary_domain)
                # Higher confidence if agent has explicit capability match
                capabilities_lower = [c.lower() for c in specialist.capabilities]
                has_capability = primary_domain.lower() in capabilities_lower
                confidence = 0.9 if has_capability else min(0.85, 0.5 + importance * 0.35)

                assignments.append(
                    AgentAssignment(agent_id=specialist.agent_id, role="specialist", confidence=confidence)
                )

        elif mode == CollaborationMode.RED_BLUE:
            # Best agent is blue (proposer), second is red (attacker)
            # In adversarial mode, the top agent proposes, second attacks
            blue = ranked_agents[0] if ranked_agents else None
            red = get_next_best({blue.agent_id} if blue else set())

            if blue:
                assignments.append(
                    AgentAssignment(agent_id=blue.agent_id, role="blue", subtask="propose_and_defend", confidence=0.8)
                )
            if red:
                assignments.append(
                    AgentAssignment(agent_id=red.agent_id, role="red", subtask="attack_and_verify", confidence=0.8)
                )

        return assignments

    # =========================================================================
    # V7.6 Phase 10b: Memory-Augmented Selection
    # =========================================================================

    def _apply_memory_boost(
        self, analysis: TaskAnalysis, mode_scores: dict[CollaborationMode, float]
    ) -> tuple[CollaborationMode | None, dict | None]:
        """
        Apply memory boost to mode scores based on similar tasks.

        V7.6 Phase 10b: Consults SuccessMemory to find similar tasks
        and boosts the mode that worked for them.

        Args:
            analysis: TaskAnalysis with raw_input description.
            mode_scores: Dictionary of mode scores (modified in-place).

        Returns:
            Tuple of (boosted_mode, boost_info) or (None, None).
        """
        if not self.success_memory:
            return None, None

        # Get task description
        description = getattr(analysis, "raw_input", "")
        if not description:
            return None, None

        # V8.8 (GROK-002): Extract domains for domain-aware mode selection
        query_domains = None
        if hasattr(analysis, "domains") and analysis.domains:
            query_domains = [d.value if hasattr(d, "value") else str(d) for d in analysis.domains]

        # Find similar tasks with domain weighting
        result = self.success_memory.get_best_mode_for_similar(
            query=description,
            min_similarity=self.MEMORY_MIN_SIMILARITY,
            query_domains=query_domains,  # V8.8: Domain-aware boost
        )

        if not result:
            return None, None

        recommended_mode, similar_task_id, similarity = result

        # Map mode string to enum
        boosted_mode = None
        for mode in CollaborationMode:
            if mode.value.lower() == recommended_mode.lower():
                boosted_mode = mode
                break

        if not boosted_mode or boosted_mode not in mode_scores:
            return None, None

        # Calculate boost based on similarity level
        if similarity > 0.5:
            boost = self.MEMORY_BOOST_HIGH
        elif similarity > 0.3:
            boost = self.MEMORY_BOOST_MEDIUM
        else:
            boost = self.MEMORY_BOOST_LOW

        # Apply boost
        original_score = mode_scores[boosted_mode]
        mode_scores[boosted_mode] = min(1.0, original_score + boost)

        # Store match info
        boost_info = {
            "mode": boosted_mode.value,
            "similar_task_id": similar_task_id,
            "similarity": round(similarity, 3),
            "boost_applied": boost,
            "original_score": round(original_score, 3),
            "new_score": round(mode_scores[boosted_mode], 3),
        }

        self._last_memory_match = boost_info

        return boosted_mode, boost_info

    def _apply_auto_memory_boost(
        self, analysis: TaskAnalysis, mode_scores: dict[CollaborationMode, float]
    ) -> tuple[dict | None, str | None]:
        """
        Apply AutoMemory boost using gradient confidence.

        V7.6 Phase 13d: Uses task_type lookup (not semantic similarity)
        to suggest optimal mode and lead agent.

        Gradient Confidence:
        - >= 0.8: +0.30 boost (VERY_HIGH)
        - >= 0.7: +0.25 boost (HIGH)
        - >= 0.5: +0.10 boost (LOW)
        - < 0.5: ignore suggestion

        Args:
            analysis: TaskAnalysis with primary_domain.
            mode_scores: Dictionary of mode scores (modified in-place).

        Returns:
            Tuple of (auto_memory_info, suggested_lead) or (None, None).
        """
        if not self.auto_memory:
            return None, None

        # Get task type from primary domain
        task_type = analysis.primary_domain.value.lower()

        # Get recommendation from AutoMemory
        try:
            recommendation = self.auto_memory.get_recommendation(task_type)
        except Exception as e:
            _logger.warning(f"AutoMemory.get_recommendation failed: {e}")
            return None, None

        if not recommendation:
            return None, None

        suggested_mode = recommendation.get("mode")
        suggested_lead = recommendation.get("lead")
        confidence = recommendation.get("confidence", 0.0)
        modes_to_avoid = recommendation.get("modes_to_avoid", [])

        # Check minimum confidence threshold
        if confidence < self.AUTO_MEMORY_MIN_CONFIDENCE:
            _logger.debug(f"AutoMemory confidence {confidence:.2f} below threshold {self.AUTO_MEMORY_MIN_CONFIDENCE}")
            return None, None

        # Calculate boost based on gradient confidence
        if confidence >= 0.8:
            boost = self.AUTO_MEMORY_BOOST_VERY_HIGH
        elif confidence >= 0.7:
            boost = self.AUTO_MEMORY_BOOST_HIGH
        else:  # >= 0.5
            boost = self.AUTO_MEMORY_BOOST_LOW

        # Apply boost to suggested mode
        boosted_mode = None
        original_score = None
        if suggested_mode:
            for mode in CollaborationMode:
                if mode.value.lower() == suggested_mode.lower():
                    boosted_mode = mode
                    break

            if boosted_mode and boosted_mode in mode_scores:
                original_score = mode_scores[boosted_mode]
                mode_scores[boosted_mode] = min(1.0, original_score + boost)
                _logger.debug(
                    f"AutoMemory boosted {boosted_mode.value}: "
                    f"{original_score:.3f} -> {mode_scores[boosted_mode]:.3f} "
                    f"(confidence={confidence:.2f})"
                )

        # Apply penalty to modes to avoid
        for mode_name in modes_to_avoid:
            for mode in CollaborationMode:
                if mode.value.lower() == mode_name.lower():
                    if mode in mode_scores:
                        mode_scores[mode] = max(0.0, mode_scores[mode] - 0.15)
                    break

        # Store suggestion info
        auto_memory_info = {
            "task_type": task_type,
            "suggested_mode": suggested_mode,
            "suggested_lead": suggested_lead,
            "confidence": round(confidence, 3),
            "boost_applied": boost,
            "original_score": round(original_score, 3) if original_score is not None else None,
            "new_score": round(mode_scores[boosted_mode], 3) if boosted_mode else None,
            "modes_to_avoid": modes_to_avoid,
        }

        self._last_auto_memory_suggestion = auto_memory_info

        # Return lead only if confidence > 0.7 (for lead bonus in _assign_agents)
        return_lead = suggested_lead if confidence > 0.7 else None

        return auto_memory_info, return_lead

    # =========================================================================
    # V11.2 MEMORIA: Unified Memory Boost
    # =========================================================================

    def _apply_unified_memory_boost(
        self, analysis: TaskAnalysis, mode_scores: dict[CollaborationMode, float]
    ) -> tuple[str | None, str | None, dict | None]:
        """
        Apply unified memory boost using MemoryCoordinator.

        V11.2 MEMORIA: Replaces separate _apply_memory_boost and
        _apply_auto_memory_boost when coordinator is available.

        Args:
            analysis: TaskAnalysis with raw_input and domains.
            mode_scores: Dictionary of mode scores (modified in-place).

        Returns:
            Tuple of (boosted_mode_name, suggested_lead, unified_info) or (None, None, None).
        """
        if not self.memory_coordinator:
            return None, None, None

        # Get task description and type
        description = getattr(analysis, "raw_input", "")
        if not description:
            return None, None, None

        task_type = analysis.primary_domain.value.lower()

        # Extract domains for query
        domains = None
        if hasattr(analysis, "domains") and analysis.domains:
            domains = [d.value if hasattr(d, "value") else str(d) for d in analysis.domains]

        # Get unified recommendation
        try:
            rec = self.memory_coordinator.get_recommendation(
                task_description=description, task_type=task_type, domains=domains
            )
        except Exception as e:
            _logger.warning(f"MemoryCoordinator.get_recommendation failed: {e}")
            return None, None, None

        # Check minimum confidence
        if rec.confidence < 0.3:
            _logger.debug(f"[MEMORIA] Unified confidence {rec.confidence:.2f} below threshold")
            return None, None, None

        # Apply boost to suggested mode
        boosted_mode_name = None
        original_score = None

        if rec.mode:
            for mode in CollaborationMode:
                if mode.value.lower() == rec.mode.lower():
                    if mode in mode_scores:
                        original_score = mode_scores[mode]
                        # Boost scales with confidence: 0.1 to 0.3
                        boost = 0.1 + (rec.confidence * 0.2)
                        mode_scores[mode] = min(1.0, original_score + boost)
                        boosted_mode_name = mode.value
                        _logger.debug(
                            f"[MEMORIA] Boosted {mode.value}: {original_score:.3f} -> "
                            f"{mode_scores[mode]:.3f} (conf={rec.confidence:.2f})"
                        )
                    break

        # Apply penalties to modes to avoid
        for mode_name in rec.modes_to_avoid:
            for mode in CollaborationMode:
                if mode.value.lower() == mode_name.lower():
                    if mode in mode_scores:
                        mode_scores[mode] = max(0.0, mode_scores[mode] - 0.15)
                        _logger.debug(f"[MEMORIA] Penalized {mode.value} (-0.15)")
                    break

        # Store unified recommendation info
        unified_info = rec.to_dict()
        unified_info["original_score"] = round(original_score, 3) if original_score is not None else None
        unified_info["new_score"] = (
            round(mode_scores.get(next((m for m in CollaborationMode if m.value == boosted_mode_name), None), 0), 3)
            if boosted_mode_name
            else None
        )

        self._last_unified_recommendation = unified_info

        # Return lead if confidence > 0.5 (for agent assignment boost)
        return_lead = rec.lead if rec.confidence > 0.5 else None

        return boosted_mode_name, return_lead, unified_info

    def _generate_reasoning(
        self,
        mode: CollaborationMode,
        analysis: TaskAnalysis,
        scores: dict[CollaborationMode, float],
        memory_boost_info: dict | None = None,
        auto_memory_info: dict | None = None,
    ) -> str:
        """
        Generate human-readable reasoning for mode selection.

        V7.5 Phase 5b: Agent-agnostic reasoning.
        V7.6 Phase 10b: Includes memory influence if applicable.
        V7.6 Phase 13d: Includes AutoMemory influence if applicable.
        """
        char = get_mode_characteristics(mode)

        reasons = []

        # V7.6 Phase 10b: Memory-augmented selection (SuccessMemory)
        if memory_boost_info and memory_boost_info.get("mode") == mode.value:
            task_id = memory_boost_info.get("similar_task_id", "unknown")[:12]
            similarity = memory_boost_info.get("similarity", 0)
            reasons.append(f"Boosted by SuccessMemory (similar to {task_id}, {similarity:.0%})")

        # V7.6 Phase 13d: AutoMemory influence
        if auto_memory_info and auto_memory_info.get("suggested_mode"):
            suggested = auto_memory_info.get("suggested_mode", "")
            if suggested.lower() == mode.value.lower():
                confidence = auto_memory_info.get("confidence", 0)
                boost = auto_memory_info.get("boost_applied", 0)
                reasons.append(f"AutoMemory: {suggested} (conf={confidence:.0%}, +{boost:.0%})")

        # Complexity reason
        complexity_name = analysis.complexity.name.lower()
        reasons.append(f"Task complexity: {complexity_name}")

        # Domain reason
        domain_str = ", ".join(d.value for d in analysis.domains[:2])
        reasons.append(f"Domains: {domain_str}")

        # Agent fit reason - V7.5 Phase 5b: Use generic message
        if analysis.recommended_lead:
            reasons.append(f"Recommended lead: {analysis.recommended_lead}")
        else:
            reasons.append("Agent selection based on capability scores")

        # Mode-specific reason
        reasons.append(char.when_to_use)

        # Score
        reasons.append(f"Selection confidence: {scores[mode]:.0%}")

        return " | ".join(reasons)

    def _find_best_spawned_specialist(
        self, spawned_agents: list[AgentProfile], analysis: TaskAnalysis
    ) -> AgentProfile | None:
        """
        Find the best spawned agent for a specialist role.

        V7.5 HIVE MIND: Matches spawned agent capabilities against task domains.

        Args:
            spawned_agents: List of spawned agents
            analysis: Task analysis with domain info

        Returns:
            Best matching AgentProfile or None
        """
        if not spawned_agents:
            return None

        primary_domain = analysis.primary_domain.value.lower()
        best_agent = None
        best_score = 0.0

        for agent in spawned_agents:
            # Check if agent's capabilities match task domain
            capabilities_lower = [c.lower() for c in agent.capabilities]

            # Direct domain match
            if primary_domain in capabilities_lower:
                score = 1.0
            # Partial match (domain word in capability)
            elif any(primary_domain in cap for cap in capabilities_lower):
                score = 0.8
            # Check DyLAN importance for this domain
            else:
                score = agent.get_task_importance(primary_domain)

            if score > best_score:
                best_score = score
                best_agent = agent

        # Only return if score is above threshold
        if best_score >= 0.5:
            return best_agent
        return None

    def _assign_spawned_specialist(
        self, spawned_agents: list[AgentProfile], analysis: TaskAnalysis
    ) -> list[AgentAssignment]:
        """
        Assign a spawned agent as specialist (fallback when no internal agents).

        V7.5 HIVE MIND: Used when gemini/claude are unavailable.
        """
        best = self._find_best_spawned_specialist(spawned_agents, analysis)
        if best:
            return [AgentAssignment(agent_id=best.agent_id, role="specialist", confidence=0.7)]

        # Last resort: use first available spawned agent
        if spawned_agents:
            return [AgentAssignment(agent_id=spawned_agents[0].agent_id, role="specialist", confidence=0.5)]

        return []

    def _create_default_agents(self) -> list[AgentProfile]:
        """Create default agent profiles when pool unavailable"""
        return [
            AgentProfile(agent_id="gemini_primary", provider="gemini", model="gemini-3-pro-preview"),
            AgentProfile(agent_id="claude_opus", provider="claude", model="claude-opus-4-6-20250116"),
        ]

    def _record_selection(self, analysis: TaskAnalysis, proposal: ModeProposal):
        """Record selection for future analysis"""
        record = {
            "timestamp": datetime.now().isoformat(),
            "task_complexity": analysis.complexity.name,
            "primary_domain": analysis.primary_domain.value,
            "selected_mode": proposal.mode.value,
            "confidence": proposal.confidence,
        }
        self.selection_history.append(record)

        # Keep only last 100 selections
        if len(self.selection_history) > 100:
            self.selection_history = self.selection_history[-100:]

    def get_selection_stats(self) -> dict:
        """Get statistics about mode selections"""
        if not self.selection_history:
            return {"total_selections": 0}

        mode_counts: dict[str, int] = {}
        for record in self.selection_history:
            mode = record["selected_mode"]
            mode_counts[mode] = mode_counts.get(mode, 0) + 1

        avg_confidence = sum(r["confidence"] for r in self.selection_history) / len(self.selection_history)

        return {
            "total_selections": len(self.selection_history),
            "mode_distribution": mode_counts,
            "average_confidence": round(avg_confidence, 3),
        }
