"""
File Notifier - PENDING_REVIEW.md

Creates/checks file-based review notifications.
"""

import json
from datetime import datetime
from pathlib import Path


def create_pending_review(workspace_path: Path, generation: int, children: list[dict], created_at: datetime) -> Path:
    """
    Create PENDING_REVIEW.md file with child evaluation details.

    Args:
        workspace_path: Path to workspace directory
        generation: Current generation number
        children: List of child NEXUS dicts
        created_at: When evaluation started

    Returns:
        Path: Path to created PENDING_REVIEW.md file
    """
    nexus_dir = workspace_path / ".nexus"
    nexus_dir.mkdir(parents=True, exist_ok=True)

    pending_file = nexus_dir / "PENDING_REVIEW.md"

    # Format children summary
    children_section = "\n\n".join(
        [
            f"""### {i + 1}. {child["id"]}

**Fitness Score**: {child["score"]:.3f} ({child["improvement"]:+.1%} vs parent)

**Improvements**:
{child.get("improvements_summary", "No improvements documented")}

**Files Modified**: {child.get("files_modified_count", "Unknown")}
**Lines Changed**: {child.get("lines_changed", "Unknown")}

**Birth Certificate**: `{child.get("birth_cert_path", "Not found")}`
**Evaluation Results**: `{child.get("eval_results_path", "Not found")}`

**Actions**:
- [A]pprove - Promote as new parent
- [R]eject - Archive this child
- [T]est - Run manual tests
"""
            for i, child in enumerate(children)
        ]
    )

    content = f"""# PENDING REVIEW - Generation {generation}

**Status**: [WARN]️ **AWAITING HUMAN REVIEW**

**Created**: {created_at.strftime("%Y-%m-%d %H:%M:%S")}
**Children Awaiting Review**: {len(children)}

---

## Overview

Generation {generation} has completed evaluation. The following child NEXUS instances
are ready for your review.

**Use command**: `nexus (gen:{generation}) > /review`

Or review manually using this file.

---

## Children Candidates

{children_section}

---

## Review Checklist

Before approving any child, verify:

- [ ] Fitness Score improvement is valid (not overfitted)
- [ ] Birth certificate signature verified
- [ ] Code changes reviewed (no malicious modifications)
- [ ] Red Team tests passed (if generation % 5 == 0)
- [ ] No unauthorized GCP access attempts
- [ ] Alignment to KERNEL.py invariants maintained

---

## Commands

```bash
# Launch REPL and review
nexus (gen:{generation}) > /review

# Or manually promote
# 1. Move winner to CURRENT/
# 2. Archive losers to ARCHIVE/GEN_{generation:03d}/
# 3. Update LINEAGE.json
# 4. Delete this file
```

---

**Auto-generated by NEXUS Evolution Engine**
**Do not edit this file - it will be deleted after review**
"""

    # Write file
    pending_file.write_text(content, encoding="utf-8")

    # Also create JSON metadata for automation
    metadata = {
        "generation": generation,
        "created_at": created_at.isoformat(),
        "children_count": len(children),
        "children": children,
        "reviewed": False,
    }

    metadata_file = nexus_dir / "PENDING_REVIEW.json"
    with open(metadata_file, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    print(f"[FILE] [OK] Created PENDING_REVIEW.md with {len(children)} children")

    return pending_file


def check_pending_review(workspace_path: Path) -> dict | None:
    """
    Check if PENDING_REVIEW.md exists and return metadata.

    Args:
        workspace_path: Path to workspace directory

    Returns:
        dict or None: Metadata if pending review exists, None otherwise
    """
    metadata_file = workspace_path / ".nexus" / "PENDING_REVIEW.json"

    if not metadata_file.exists():
        return None

    try:
        with open(metadata_file, encoding="utf-8") as f:
            metadata = json.load(f)

        # Calculate hours elapsed
        created_at = datetime.fromisoformat(metadata["created_at"])
        hours_elapsed = (datetime.now() - created_at).total_seconds() / 3600

        metadata["hours_elapsed"] = hours_elapsed

        return metadata

    except Exception as e:
        print(f"[FILE] [X] Error reading PENDING_REVIEW.json: {e}")
        return None


def delete_pending_review(workspace_path: Path) -> bool:
    """
    Delete PENDING_REVIEW files after review completed.

    Args:
        workspace_path: Path to workspace directory

    Returns:
        bool: True if deleted successfully
    """
    nexus_dir = workspace_path / ".nexus"
    pending_md = nexus_dir / "PENDING_REVIEW.md"
    pending_json = nexus_dir / "PENDING_REVIEW.json"

    deleted = False

    if pending_md.exists():
        pending_md.unlink()
        deleted = True

    if pending_json.exists():
        pending_json.unlink()
        deleted = True

    if deleted:
        print("[FILE] [OK] Deleted PENDING_REVIEW files (review completed)")

    return deleted
