"""
NEXUS V12.4 - Intelligence Package

P5.6 Phase 6: Package Consolidation

Consolidated intelligence components for swarm coordination, agent evolution, advanced reasoning, and hive mind orchestration.

## 📦 Subpackages

- **swarm/**: Hybrid Swarm Engine with 6 collaboration modes (PARALLEL, SEQUENTIAL, LEAD_SUPPORT, PING_PONG, SPECIALIST, RED_BLUE)
- **evolution/**: Self-modification, lineage tracking, tiered validation, agent reaper, auto-specializer
- **reasoning/**: Graph of Thought (GoT), metacognitive monitoring, reasoning quality scoring, confidence calibration
- **hive_mind/**: TRUE HIVE MIND with 7 phases, adaptive debate, knowledge consolidation, swarm bridge

## 🎯 Key Features

### Hybrid Swarm Engine
```python
from core.intelligence import HybridSwarmEngine, CollaborationMode

engine = HybridSwarmEngine(agent_pool, model_router, config)
result = await engine.process_task("Fix the auth bug", blackboard)
```

### Evolution & Lineage
```python
from core.intelligence import EvolutionManager, TieredValidator

manager = EvolutionManager(...)
result = await manager.evolve_agent(task="performance")
```

### Advanced Reasoning
```python
from core.intelligence import MetacognitiveMonitor, ConfidenceCalibrator

monitor = get_metacognitive_monitor()
anomaly = monitor.detect_anomaly(agent_response)
```

### TRUE HIVE MIND
```python
from core.intelligence import TrueHiveMind

hive = TrueHiveMind(workspace_path, config)
result = await hive.process_task("Complex multi-step task")
```

## 📊 Migration Impact

**Statistics:**
- Files migrated: TBD
- Import updates: TBD
- Commit: TBD
- Impact: TBD

---
**Status:** P5.6 Phase 6 IN PROGRESS | **Version:** V12.4
"""

# Swarm exports (96 items)
# Evolution exports (30 items)
from core.intelligence.evolution import (
    AgentPerformance,
    AgentReaper,
    ArchivalCandidate,
    ArchiveResult,
    AutoPromotionDecision,
    AutoSpecializer,
    BrainstormResult,
    ChildCreationResult,
    ChildValidator,
    DomainProfile,
    EvaluationResult,
    EvolutionContext,
    EvolutionManager,
    EvolutionPhaseStatus,
    EvolutionResult,
    EvolutionService,
    EvolutionServiceResult,
    EvolutionStatus,
    FullValidationResult,
    LineageNode,
    MutationProposal,
    MutationRecord,
    MutationTracker,
    PromotionResult,
    ReaperConfig,
    ReaperReport,
    SafetyGate,
    SpecializationConfig,
    SpecializationProposal,
    SpecializationResult,
    StrategyApplication,
    StrategyMetrics,
    StrategyPerformanceTracker,
    StrategyRecommendation,
    TieredValidationResult,
    TieredValidator,
    TierResult,
    TrackerStats,
    ValidationTier,
    _get_evolution_service,
    add_child,
    compare_to_parent,
    get_ancestry,
    get_mutation_tracker,
    get_strategy_tracker,
    load_lineage,
    reset_mutation_tracker,
    reset_strategy_tracker,
    run_benchmarks,
    select_winner,
    sign_birth_certificate,
)
from core.intelligence.evolution import (
    ValidationResult as EvolutionValidationResult,
)

# Hive Mind exports (48 items)
from core.intelligence.hive_mind import (
    PHASE_GUARDS,
    PHASE_ORDER,
    AdaptiveDebateConfig,
    AgentArchitecture,
    AgentReflection,
    AgentRegistry,
    AgentRetention,
    AgentSpec,
    AnalysisComparison,
    AuditPattern,
    AuditStats,
    BreakpointOption,
    BreakpointRequest,
    BreakpointResponse,
    ConsensusReport,
    ConsensusTracker,
    CostEstimator,
    DebateArgument,
    DebateParams,
    DebateResult,
    DecisionAudit,
    Disagreement,
    ExecutionIssue,
    FailureDiagnosis,
    HiveMindContextManager,
    HiveMindResult,
    HiveMindState,
    HivePhase,
    IndependentAnalysis,
    KnowledgeConsolidation,
    MonitoredStepResult,
    MultiAgentReflexion,
    PhaseAuditLogger,
    PhaseAuditReport,
    PhaseCheckpoint,
    PhaseCoordinator,
    PhaseState,
    PhaseTransition,
    ReflexionMode,
    ReflexionStats,
    ReflexionSynthesis,
    RetentionDecision,
    RetryDecision,
    SagaContext,
    SagaManager,
    StrategyBlacklist,
    SwarmBridge,
    SwarmDelegationResult,
    TopicConsensus,
    TransitionResult,
    TrueHiveMind,
    UserBreakpoint,
    UserInteractionHandler,
    create_bridge_for_phase,
    get_consensus_tracker,
    get_multi_agent_reflexion,
    get_phase_audit_logger,
    get_phase_coordinator,
    reset_consensus_tracker,
    reset_multi_agent_reflexion,
    reset_phase_audit_logger,
    reset_phase_coordinator,
    suggest_mode_for_subtask,
)
from core.intelligence.hive_mind import (
    TaskComplexity as HiveTaskComplexity,
)

# Reasoning exports (60+ items)
from core.intelligence.reasoning import (
    GOT_AVAILABLE,
    AdmissibilityResult,
    AgentCalibrationProfile,
    AgentReasoningProfile,
    AgentStatus,
    AgentTrajectory,
    AnomalyScore,
    CalibratedConfidence,
    CalibratorStats,
    ChainSummary,
    Classification,
    ClassifierStats,
    CognitiveDegradationDetector,
    ConfidenceBias,
    ConfidenceCalibrator,
    ConformityAnalysis,
    ConsensusVerifier,
    DegradationReason,
    DegradationSignal,
    DetectorStats,
    DimensionScore,
    EvalDimension,
    EvaluationPanel,
    FailureCategory,
    FailureClassifier,
    FaultDetector,
    FaultStatus,
    GraphOfThought,
    GuardStats,
    InspectionResult,
    InspectorGuard,
    IssuePattern,
    MetacognitiveMonitor,
    MetaPolicyMemory,
    Mitigation,
    PanelResult,
    PolicyRule,
    PropagationSignal,
    PropagatorStats,
    QualityGate,
    ReasoningEvaluation,
    ReasoningQualityScorer,
    RiskLevel,
    RuleCategory,
    ScorerStats,
    ThoughtEvaluator,
    ThoughtGraph,
    ThoughtNode,
    ThoughtScore,
    ThoughtStatus,
    ThoughtType,
    TrajectoryResult,
    TrajectoryScorer,
    UncertaintyLevel,
    UncertaintyPropagator,
    VerificationOutcome,
    estimate_complexity,
    get_confidence_calibrator,
    get_consensus_verifier,
    get_degradation_detector,
    get_evaluation_panel,
    get_failure_classifier,
    get_fault_detector,
    get_inspector_guard,
    get_meta_policy_memory,
    get_metacognitive_monitor,
    get_quality_scorer,
    get_thought_evaluator,
    get_trajectory_scorer,
    get_uncertainty_propagator,
    reset_confidence_calibrator,
    reset_consensus_verifier,
    reset_degradation_detector,
    reset_evaluation_panel,
    reset_failure_classifier,
    reset_fault_detector,
    reset_inspector_guard,
    reset_meta_policy_memory,
    reset_metacognitive_monitor,
    reset_quality_scorer,
    reset_thought_evaluator,
    reset_trajectory_scorer,
    reset_uncertainty_propagator,
    should_monitor_metacognition,
)
from core.intelligence.reasoning import (
    EvaluationResult as ThoughtEvaluationResult,
)
from core.intelligence.reasoning import (
    EvaluatorStats as ThoughtEvaluatorStats,
)
from core.intelligence.reasoning import (
    TaskComplexity as ReasoningTaskComplexity,
)
from core.intelligence.reasoning import (
    VerificationResult as ConsensusVerificationResult,
)
from core.intelligence.swarm import (
    EXECUTOR_REGISTRY,
    MODE_CHARACTERISTICS,
    # Mode Selector
    AgentAssignment,
    # Agent Metrics
    AgentInvocationResult,
    AgentPool,
    AgentProfile,
    AgentResponse,
    AgentRoleProfile,
    # V12.4: Agent Role Tracker
    AgentRoleTracker,
    AgentSession,
    AggregatorStats,
    AssignerStats,
    CapabilityProposal,
    # Collaboration Modes
    CollaborationMode,
    CompletionCriteria,
    CoordinationType,
    # V12.4: Dynamic Role Assigner
    DynamicRoleAssigner,
    EvaluatorStats,
    ExecutionContext,
    ExecutionResult,
    # Mode Executors
    ExecutionStatus,
    HybridNegotiationMessage,
    HybridSwarmEngine,
    LeadSupportExecutor,
    MergeResult,
    MergeStrategy,
    ModeCharacteristics,
    ModeEffectiveness,
    # V12.4: Mode Effectiveness Evaluator
    ModeEffectivenessEvaluator,
    ModeEffectivenessSummary,
    ModeEvaluation,
    ModeExecutor,
    ModeProposal,
    ModeSelector,
    ModeSuggestion,
    NegotiationProposal,
    NegotiationProtocol,
    NegotiationRecord,
    NegotiationResult,
    NegotiationStats,
    # Negotiation Protocol
    NegotiationStatus,
    # V12.4: Negotiation Tracker
    NegotiationTracker,
    NegotiationTurn,
    ParallelExecutor,
    PingPongExecutor,
    QueueStats,
    RedBlueExecutor,
    # V12.4: Result Aggregator
    ResultAggregator,
    RoleAssignment,
    RoleAssignmentResult,
    RoleScore,
    RoleTrackerStats,
    RoleType,
    # V12.4: Scaling Heuristics
    ScalingHeuristicEvaluator,
    ScalingRecommendation,
    ScalingStats,
    SequentialExecutor,
    SessionMode,
    # Session Manager
    SessionStatus,
    SpecialistExecutor,
    # V12.4: Strategy Memory
    StrategyMemory,
    StrategyRecord,
    StrategyStats,
    # Hybrid Swarm Engine
    SwarmPhase,
    SwarmResult,
    # Service Layer
    SwarmService,
    SwarmServiceResult,
    SwarmSessionManager,
    SwarmStatus,
    SwarmTask,
    # V12.4: Task Queue
    SwarmTaskQueue,
    SwarmTaskStatus,
    TaskAnalysis,
    TaskAnalyzer,
    TaskCharacteristic,
    # Task Completion Validator
    TaskCompletionValidator,
    # Task Analyzer
    TaskComplexity,
    TaskDomain,
    TaskSession,
    ValidationResult,
    create_default_pool,
    extract_negotiate_json,
    generate_task_id,
    get_adaptive_max_rounds,
    get_adversarial_modes,
    get_aggregator,
    get_all_modes,
    get_dynamic_role_assigner,
    get_executor,
    get_mode_characteristics,
    get_mode_evaluator,
    get_negotiation_tracker,
    get_parallel_modes,
    get_role_tracker,
    get_scaling_heuristics,
    get_strategy_memory,
    get_task_queue,
    reset_aggregator,
    reset_dynamic_role_assigner,
    reset_mode_evaluator,
    reset_negotiation_tracker,
    reset_role_tracker,
    reset_scaling_heuristics,
    reset_strategy_memory,
    reset_task_queue,
    suggest_mode_for_complexity,
)

__all__ = [
    # Swarm (96 items)
    "AgentInvocationResult",
    "AgentProfile",
    "AgentPool",
    "create_default_pool",
    "CollaborationMode",
    "ModeCharacteristics",
    "MODE_CHARACTERISTICS",
    "get_mode_characteristics",
    "get_all_modes",
    "get_adversarial_modes",
    "get_parallel_modes",
    "suggest_mode_for_complexity",
    "TaskComplexity",
    "TaskDomain",
    "TaskAnalysis",
    "TaskAnalyzer",
    "AgentAssignment",
    "ModeProposal",
    "ModeSelector",
    "NegotiationStatus",
    "NegotiationProposal",
    "HybridNegotiationMessage",
    "NegotiationResult",
    "NegotiationProtocol",
    "extract_negotiate_json",
    "ExecutionStatus",
    "AgentResponse",
    "ExecutionContext",
    "ExecutionResult",
    "ModeExecutor",
    "ParallelExecutor",
    "SequentialExecutor",
    "LeadSupportExecutor",
    "PingPongExecutor",
    "SpecialistExecutor",
    "RedBlueExecutor",
    "EXECUTOR_REGISTRY",
    "get_executor",
    "SwarmPhase",
    "SwarmResult",
    "HybridSwarmEngine",
    "SessionStatus",
    "SessionMode",
    "AgentSession",
    "TaskSession",
    "SwarmSessionManager",
    "generate_task_id",
    "TaskCompletionValidator",
    "CompletionCriteria",
    "ValidationResult",
    "get_adaptive_max_rounds",
    "SwarmService",
    "SwarmServiceResult",
    "SwarmStatus",
    "SwarmTaskQueue",
    "SwarmTask",
    "SwarmTaskStatus",
    "QueueStats",
    "get_task_queue",
    "reset_task_queue",
    "ResultAggregator",
    "MergeStrategy",
    "MergeResult",
    "AggregatorStats",
    "get_aggregator",
    "reset_aggregator",
    "StrategyMemory",
    "StrategyRecord",
    "ModeEffectiveness",
    "ModeSuggestion",
    "StrategyStats",
    "get_strategy_memory",
    "reset_strategy_memory",
    "NegotiationTracker",
    "NegotiationTurn",
    "NegotiationRecord",
    "NegotiationStats",
    "get_negotiation_tracker",
    "reset_negotiation_tracker",
    "ModeEffectivenessEvaluator",
    "ModeEvaluation",
    "ModeEffectivenessSummary",
    "EvaluatorStats",
    "get_mode_evaluator",
    "reset_mode_evaluator",
    "AgentRoleTracker",
    "RoleAssignment",
    "AgentRoleProfile",
    "RoleTrackerStats",
    "get_role_tracker",
    "reset_role_tracker",
    "DynamicRoleAssigner",
    "CapabilityProposal",
    "RoleScore",
    "RoleAssignmentResult",
    "RoleType",
    "AssignerStats",
    "get_dynamic_role_assigner",
    "reset_dynamic_role_assigner",
    "ScalingHeuristicEvaluator",
    "ScalingRecommendation",
    "CoordinationType",
    "TaskCharacteristic",
    "ScalingStats",
    "get_scaling_heuristics",
    "reset_scaling_heuristics",
    # Evolution (30 items)
    "EvolutionManager",
    "EvolutionService",
    "EvolutionServiceResult",
    "_get_evolution_service",
    "MutationProposal",
    "BrainstormResult",
    "ChildCreationResult",
    "EvaluationResult",
    "PromotionResult",
    "ArchiveResult",
    "EvolutionResult",
    "SpecializationResult",
    "EvolutionStatus",
    "EvolutionContext",
    "EvolutionPhaseStatus",
    "load_lineage",
    "add_child",
    "get_ancestry",
    "sign_birth_certificate",
    "run_benchmarks",
    "compare_to_parent",
    "select_winner",
    "ChildValidator",
    "EvolutionValidationResult",
    "FullValidationResult",
    "SafetyGate",
    "AutoPromotionDecision",
    "TieredValidator",
    "ValidationTier",
    "TieredValidationResult",
    "TierResult",
    "AgentReaper",
    "ReaperConfig",
    "ReaperReport",
    "ArchivalCandidate",
    "AutoSpecializer",
    "SpecializationConfig",
    "SpecializationProposal",
    "DomainProfile",
    "MutationTracker",
    "MutationRecord",
    "AgentPerformance",
    "LineageNode",
    "get_mutation_tracker",
    "reset_mutation_tracker",
    "StrategyPerformanceTracker",
    "StrategyApplication",
    "StrategyMetrics",
    "StrategyRecommendation",
    "TrackerStats",
    "get_strategy_tracker",
    "reset_strategy_tracker",
    # Reasoning (60+ items)
    "GOT_AVAILABLE",
    "GraphOfThought",
    "ThoughtNode",
    "ThoughtGraph",
    "ThoughtStatus",
    "ThoughtType",
    "ThoughtEvaluator",
    "ThoughtScore",
    "ThoughtEvaluationResult",
    "ThoughtEvaluatorStats",
    "get_thought_evaluator",
    "reset_thought_evaluator",
    "ReasoningQualityScorer",
    "ReasoningEvaluation",
    "AgentReasoningProfile",
    "ScorerStats",
    "get_quality_scorer",
    "reset_quality_scorer",
    "CognitiveDegradationDetector",
    "DegradationSignal",
    "DegradationReason",
    "Mitigation",
    "DetectorStats",
    "get_degradation_detector",
    "reset_degradation_detector",
    "EvaluationPanel",
    "EvalDimension",
    "DimensionScore",
    "PanelResult",
    "get_evaluation_panel",
    "reset_evaluation_panel",
    "ConsensusVerifier",
    "VerificationOutcome",
    "ConsensusVerificationResult",
    "QualityGate",
    "get_consensus_verifier",
    "reset_consensus_verifier",
    "MetaPolicyMemory",
    "PolicyRule",
    "RuleCategory",
    "AdmissibilityResult",
    "get_meta_policy_memory",
    "reset_meta_policy_memory",
    "MetacognitiveMonitor",
    "AnomalyScore",
    "get_metacognitive_monitor",
    "reset_metacognitive_monitor",
    "InspectorGuard",
    "InspectionResult",
    "RiskLevel",
    "IssuePattern",
    "GuardStats",
    "get_inspector_guard",
    "reset_inspector_guard",
    "ConfidenceCalibrator",
    "CalibratedConfidence",
    "ConfidenceBias",
    "AgentCalibrationProfile",
    "CalibratorStats",
    "get_confidence_calibrator",
    "reset_confidence_calibrator",
    "TrajectoryScorer",
    "TrajectoryResult",
    "AgentTrajectory",
    "ConformityAnalysis",
    "get_trajectory_scorer",
    "reset_trajectory_scorer",
    "UncertaintyPropagator",
    "PropagationSignal",
    "UncertaintyLevel",
    "ChainSummary",
    "PropagatorStats",
    "get_uncertainty_propagator",
    "reset_uncertainty_propagator",
    "FailureClassifier",
    "FailureCategory",
    "Classification",
    "ClassifierStats",
    "get_failure_classifier",
    "reset_failure_classifier",
    "FaultDetector",
    "FaultStatus",
    "AgentStatus",
    "get_fault_detector",
    "reset_fault_detector",
    "ReasoningTaskComplexity",
    "estimate_complexity",
    "should_monitor_metacognition",
    # Hive Mind (48 items)
    "HiveMindState",
    "UserBreakpoint",
    "RetentionDecision",
    "IndependentAnalysis",
    "AnalysisComparison",
    "Disagreement",
    "DebateArgument",
    "DebateResult",
    "AgentSpec",
    "AgentArchitecture",
    "ExecutionIssue",
    "MonitoredStepResult",
    "FailureDiagnosis",
    "RetryDecision",
    "KnowledgeConsolidation",
    "AgentRetention",
    "BreakpointOption",
    "BreakpointRequest",
    "BreakpointResponse",
    "AgentRegistry",
    "CostEstimator",
    "HiveMindContextManager",
    "StrategyBlacklist",
    "UserInteractionHandler",
    "AdaptiveDebateConfig",
    "DebateParams",
    "HiveTaskComplexity",
    "TrueHiveMind",
    "HiveMindResult",
    "SwarmBridge",
    "SwarmDelegationResult",
    "HivePhase",
    "suggest_mode_for_subtask",
    "create_bridge_for_phase",
    "SagaManager",
    "PhaseCheckpoint",
    "SagaContext",
    "PHASE_ORDER",
    "PHASE_GUARDS",
    "PhaseCoordinator",
    "PhaseState",
    "PhaseTransition",
    "TransitionResult",
    "get_phase_coordinator",
    "reset_phase_coordinator",
    "ConsensusTracker",
    "TopicConsensus",
    "ConsensusReport",
    "get_consensus_tracker",
    "reset_consensus_tracker",
    "PhaseAuditLogger",
    "DecisionAudit",
    "PhaseAuditReport",
    "AuditPattern",
    "AuditStats",
    "get_phase_audit_logger",
    "reset_phase_audit_logger",
    "MultiAgentReflexion",
    "AgentReflection",
    "ReflexionSynthesis",
    "ReflexionMode",
    "ReflexionStats",
    "get_multi_agent_reflexion",
    "reset_multi_agent_reflexion",
]

__version__ = "12.4.0"
