"""
NEXUS V7.8 - Dynamic Tool Manager (Phase 12.5)

Enables NEXUS agents to create and execute custom Python tools at runtime.
Tools are validated via AST analysis and executed in isolated subprocesses.

Security Layers:
1. CodeValidator - AST-based code validation (blocks dangerous patterns)
2. Subprocess isolation - Tools run in separate process
3. Timeout protection - 30 second execution limit
4. Output limits - Truncated stdout/stderr

Usage:
    manager = DynamicToolManager(workspace_path)

    # Create a tool
    result = manager.create_tool(
        name="fibonacci",
        code="def run(n): return [0,1] if n<=2 else ...",
        description="Calculate fibonacci sequence"
    )

    # Execute the tool
    result = manager.execute_tool("fibonacci", {"n": 10})

    # Delete the tool
    manager.delete_tool("fibonacci")
"""

import json
import logging
import re
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

from core.security_pkg.security.execution_policy import CodeValidator

# =============================================================================
# Constants
# =============================================================================

TOOL_TIMEOUT_SECONDS = 30
MAX_OUTPUT_SIZE = 50000  # 50KB
TOOL_PREFIX = "dyn_"  # Prefix for dynamic tool names


# =============================================================================
# Data Classes
# =============================================================================


@dataclass
class ToolCreationResult:
    """Result of tool creation."""

    success: bool
    tool_name: str
    tool_path: Path | None = None
    error: str | None = None
    validation_violations: list[str] = field(default_factory=list)


@dataclass
class ToolExecutionResult:
    """Result of tool execution."""

    success: bool
    output: str = ""
    error: str = ""
    return_code: int = -1
    timed_out: bool = False


@dataclass
class ToolMetadata:
    """Metadata for a dynamic tool."""

    name: str
    description: str
    created_at: str
    created_by: str = "agent"
    version: int = 1


# =============================================================================
# Tool Template
# =============================================================================

TOOL_TEMPLATE = '''#!/usr/bin/env python3
"""
Dynamic Tool: {name}
Description: {description}
Created: {created_at}

This tool was generated by NEXUS Dynamic Tool Manager.
DO NOT EDIT MANUALLY - regenerate via create_tool().
"""

import sys
import json

# =============================================================================
# USER CODE (validated by CodeValidator)
# =============================================================================

{user_code}

# =============================================================================
# EXECUTION WRAPPER
# =============================================================================

if __name__ == "__main__":
    try:
        # Read arguments from stdin or command line
        if len(sys.argv) > 1:
            args = json.loads(sys.argv[1])
        else:
            args = {{}}

        # Call the run() function defined in user code
        result = run(**args)

        # Output result as JSON
        print(json.dumps({{"result": result}}))

    except NameError as e:
        if "run" in str(e):
            print(json.dumps({{"error": "Tool must define a run() function"}}))
        else:
            print(json.dumps({{"error": str(e)}}))
        sys.exit(1)
    except Exception as e:
        print(json.dumps({{"error": str(e)}}))
        sys.exit(1)
'''


# =============================================================================
# DynamicToolManager
# =============================================================================


class DynamicToolManager:
    """
    Manager for creating and executing dynamic Python tools.

    V7.8 Phase 12.5: Enables agents to generate custom tools at runtime.

    Workflow:
    1. Agent requests tool creation with name, code, description
    2. CodeValidator validates the code via AST analysis
    3. Tool is saved to workspace/tools/generated/{name}.py
    4. Tool is registered in ToolManager for agent access
    5. Execution runs tool in subprocess with timeout

    Security:
    - All code validated before saving (no dangerous imports/functions)
    - Subprocess isolation (no direct exec())
    - 30 second timeout
    - Output truncation (50KB max)
    """

    def __init__(self, workspace_path: Path):
        """
        Initialize DynamicToolManager.

        Args:
            workspace_path: Root workspace directory
        """
        self.workspace_path = Path(workspace_path)
        self.tools_dir = self.workspace_path / "tools" / "generated"
        self.tools_dir.mkdir(parents=True, exist_ok=True)

        self._validator = CodeValidator()
        self._registered_tools: dict[str, ToolMetadata] = {}
        self._logger = logging.getLogger("nexus.dynamic_tools")

        # Load existing tools
        self._load_existing_tools()

    def _load_existing_tools(self) -> None:
        """Load metadata for existing generated tools."""
        for meta_file in self.tools_dir.glob("*.meta.json"):
            try:
                metadata = json.loads(meta_file.read_text(encoding="utf-8"))
                tool_name = metadata.get("name", meta_file.stem.replace(".meta", ""))
                self._registered_tools[tool_name] = ToolMetadata(**metadata)
                self._logger.debug(f"Loaded existing tool: {tool_name}")
            except Exception as e:
                self._logger.warning(f"Failed to load tool metadata {meta_file}: {e}")

    def create_tool(self, name: str, code: str, description: str = "") -> ToolCreationResult:
        """
        Create a new dynamic tool.

        Args:
            name: Tool name (alphanumeric + underscore only)
            code: Python code defining a run() function
            description: Human-readable description

        Returns:
            ToolCreationResult with success status and details
        """
        # Validate tool name
        if not self._validate_tool_name(name):
            return ToolCreationResult(
                success=False,
                tool_name=name,
                error="Invalid tool name. Use only alphanumeric characters and underscores.",
            )

        # Check if tool already exists
        tool_path = self.tools_dir / f"{name}.py"
        if tool_path.exists():
            return ToolCreationResult(
                success=False,
                tool_name=name,
                error=f"Tool '{name}' already exists. Delete it first or use a different name.",
            )

        # Validate the code
        validation = self._validator.validate_code(code)
        if not validation.is_safe:
            self._logger.warning(f"Tool '{name}' validation failed: {validation.violations}")
            return ToolCreationResult(
                success=False,
                tool_name=name,
                error="Code validation failed. Unsafe patterns detected.",
                validation_violations=validation.violations,
            )

        # Check that code defines a run() function
        if not self._has_run_function(code):
            return ToolCreationResult(success=False, tool_name=name, error="Tool code must define a 'run()' function.")

        # Generate tool file
        try:
            created_at = datetime.now().isoformat()
            tool_content = TOOL_TEMPLATE.format(
                name=name, description=description or f"Dynamic tool: {name}", created_at=created_at, user_code=code
            )

            # Write tool file
            tool_path.write_text(tool_content, encoding="utf-8")

            # Write metadata
            metadata = ToolMetadata(name=name, description=description, created_at=created_at)
            meta_path = self.tools_dir / f"{name}.meta.json"
            meta_path.write_text(json.dumps(metadata.__dict__, indent=2), encoding="utf-8")

            # Register tool
            self._registered_tools[name] = metadata

            self._logger.info(f"Created dynamic tool: {name}")

            return ToolCreationResult(success=True, tool_name=name, tool_path=tool_path)

        except Exception as e:
            self._logger.error(f"Failed to create tool '{name}': {e}")
            return ToolCreationResult(success=False, tool_name=name, error=f"Failed to create tool: {str(e)}")

    def execute_tool(self, name: str, args: dict[str, Any] | None = None) -> ToolExecutionResult:
        """
        Execute a dynamic tool.

        Args:
            name: Tool name
            args: Arguments to pass to the tool's run() function

        Returns:
            ToolExecutionResult with output and status
        """
        tool_path = self.tools_dir / f"{name}.py"

        if not tool_path.exists():
            return ToolExecutionResult(success=False, error=f"Tool '{name}' not found.")

        args = args or {}

        try:
            # Execute tool in subprocess
            result = subprocess.run(
                [sys.executable, str(tool_path), json.dumps(args)],
                capture_output=True,
                text=True,
                timeout=TOOL_TIMEOUT_SECONDS,
                cwd=str(self.workspace_path),
                encoding="utf-8",
                errors="replace",
            )

            # Truncate output if too large
            stdout = result.stdout[:MAX_OUTPUT_SIZE]
            stderr = result.stderr[:MAX_OUTPUT_SIZE]

            if len(result.stdout) > MAX_OUTPUT_SIZE:
                stdout += f"\n[Output truncated at {MAX_OUTPUT_SIZE} bytes]"
            if len(result.stderr) > MAX_OUTPUT_SIZE:
                stderr += f"\n[Error output truncated at {MAX_OUTPUT_SIZE} bytes]"

            # Parse JSON output
            try:
                output_data = json.loads(stdout)
                if "error" in output_data:
                    return ToolExecutionResult(
                        success=False, output=stdout, error=output_data["error"], return_code=result.returncode
                    )
                return ToolExecutionResult(
                    success=True,
                    output=json.dumps(output_data.get("result", stdout), indent=2),
                    error=stderr,
                    return_code=result.returncode,
                )
            except json.JSONDecodeError:
                # Non-JSON output
                return ToolExecutionResult(
                    success=result.returncode == 0, output=stdout, error=stderr, return_code=result.returncode
                )

        except subprocess.TimeoutExpired:
            self._logger.warning(f"Tool '{name}' timed out after {TOOL_TIMEOUT_SECONDS}s")
            return ToolExecutionResult(
                success=False, error=f"Tool execution timed out after {TOOL_TIMEOUT_SECONDS} seconds.", timed_out=True
            )
        except Exception as e:
            self._logger.error(f"Tool '{name}' execution failed: {e}")
            return ToolExecutionResult(success=False, error=f"Execution error: {str(e)}")

    def delete_tool(self, name: str) -> tuple[bool, str]:
        """
        Delete a dynamic tool.

        Args:
            name: Tool name

        Returns:
            Tuple of (success, message)
        """
        tool_path = self.tools_dir / f"{name}.py"
        meta_path = self.tools_dir / f"{name}.meta.json"

        if not tool_path.exists():
            return False, f"Tool '{name}' not found."

        try:
            # Delete files
            tool_path.unlink()
            if meta_path.exists():
                meta_path.unlink()

            # Unregister
            if name in self._registered_tools:
                del self._registered_tools[name]

            self._logger.info(f"Deleted dynamic tool: {name}")
            return True, f"Tool '{name}' deleted successfully."

        except Exception as e:
            self._logger.error(f"Failed to delete tool '{name}': {e}")
            return False, f"Failed to delete tool: {str(e)}"

    def list_tools(self) -> list[ToolMetadata]:
        """
        List all registered dynamic tools.

        Returns:
            List of ToolMetadata for each tool
        """
        return list(self._registered_tools.values())

    def get_tool_info(self, name: str) -> ToolMetadata | None:
        """
        Get metadata for a specific tool.

        Args:
            name: Tool name

        Returns:
            ToolMetadata or None if not found
        """
        return self._registered_tools.get(name)

    def cleanup_all(self) -> int:
        """
        Delete all dynamic tools.

        Returns:
            Number of tools deleted
        """
        count = 0
        for name in list(self._registered_tools.keys()):
            success, _ = self.delete_tool(name)
            if success:
                count += 1
        return count

    # =========================================================================
    # Private Helpers
    # =========================================================================

    def _validate_tool_name(self, name: str) -> bool:
        """Validate tool name format."""
        if not name:
            return False
        # Alphanumeric and underscore only, must start with letter
        return bool(re.match(r"^[a-zA-Z][a-zA-Z0-9_]*$", name))

    def _has_run_function(self, code: str) -> bool:
        """Check if code defines a run() function."""
        # Simple check - look for 'def run' pattern
        return bool(re.search(r"^\s*def\s+run\s*\(", code, re.MULTILINE))


# =============================================================================
# V10 PRISM: Multi-Tenant Dynamic Tool Manager Access
# =============================================================================

_manager: DynamicToolManager | None = None


def get_dynamic_tool_manager(workspace_path: Path | None = None) -> DynamicToolManager:
    """
    Get the dynamic tool manager for the current tenant context.

    V10 PRISM: Returns tenant-scoped manager via ServiceFactory.
    Falls back to global singleton if no context is active.

    Args:
        workspace_path: Workspace path (required on first call in legacy mode)

    Returns:
        DynamicToolManager instance scoped to current tenant
    """
    # V10: Try ServiceFactory first (tenant-scoped)
    try:
        from ..context import has_active_session

        if has_active_session():
            from ..factory import ServiceFactory

            return ServiceFactory.get_dynamic_tool_manager()
    except ImportError:
        pass  # context module not available, use legacy

    # Legacy fallback: global singleton
    global _manager
    if _manager is None:
        if workspace_path is None:
            raise ValueError("workspace_path required for first initialization")
        _manager = DynamicToolManager(workspace_path)
    return _manager


def reset_dynamic_tool_manager() -> None:
    """
    Reset the global dynamic tool manager (for testing).

    Note: In V10, also clears ServiceFactory cache for current tenant.
    """
    global _manager
    _manager = None

    # V10: Also clear factory cache
    try:
        from ..context import get_current_session_or_none
        from ..factory import ServiceFactory

        ctx = get_current_session_or_none()
        if ctx:
            ServiceFactory.clear_tenant_cache(ctx.tenant_id)
    except ImportError:
        pass
