"""
NEXUS V12.4 - Infrastructure Package

Consolidated infrastructure components:
- context: Multi-tenant session management and audit trails
- db: Database engine, query tracking, and connection management
- session: Session analytics and lifecycle management
- resilience: Circuit breaker, retry logic, rate limiting
- bootstrap: Bootstrap analytics and startup diagnostics

P5.6 Phase 2: Package consolidation for reduced cognitive load.
"""

# Context exports
from core.infrastructure.context import (
    DEFAULT_TENANT_ID,
    DEFAULT_USER_ID,
    DEFAULT_WORKSPACE_ID,
    AuditEntry,
    AuditStats,
    ContextAuditTrail,
    SessionContext,
    current_session,
    ensure_context,
    get_audit_trail,
    get_current_session,
    get_current_session_or_none,
    get_default_context,
    has_active_session,
    require_context,
    reset_audit_trail,
    use_context,
    use_context_async,
)
from core.infrastructure.context import (
    UserRole as SessionUserRole,  # Renamed to avoid conflict with db.UserRole
)

# Database exports (requires sqlmodel: pip install nexus-swarm-os[db])
try:
    from core.infrastructure.db import (
        DEFAULT_DB_PATH,
        DEFAULT_QUOTAS,
        PlanTier,
        QueryPerformanceStats,
        QueryPerformanceTracker,
        QueryRecord,
        Quota,
        TableProfile,
        Tenant,
        TenantStatus,
        User,
        Workspace,
        create_default_tenant,
        create_quota_for_plan,
        get_engine,
        get_query_tracker,
        get_session,
        get_tenant_by_slug,
        get_tenant_quota,
        init_db,
        reset_engine,
        reset_query_tracker,
    )

    _HAS_DB = True
except ImportError:
    _HAS_DB = False

# Bootstrap exports
from core.infrastructure.bootstrap import (
    AutoBootstrap,
    BootStepRecord,
    BootstrapService,
    ComponentProfile,
    ProjectAnalysis,
    SpawnedAgentConfig,
    SpawnedAgentLoader,
    SpinoffService,
    StartupAnalytics,
    StartupStats,
    _get_bootstrap_service,
    _get_spinoff_service,
    discover_and_register_spawned_agents,
    get_startup_analytics,
    reset_startup_analytics,
)

# Resilience exports
from core.infrastructure.resilience import (
    Checkpoint,
    CheckpointInfo,
    CheckpointManager,
    CheckResult,
    CircuitBreaker,
    CircuitOpenError,
    CircuitState,
    ComponentHealth,
    DeduplicationEntry,
    DeduplicationStats,
    EventTypeMetrics,
    ExchangeRecord,
    FilterStats,
    HealthReport,
    HealthStatus,
    Intervention,
    InterventionAction,
    InterventionType,
    ProviderLimits,
    RateLimiter,
    RequestDeduplicator,
    ResilienceEvent,
    ResilienceEventTracker,
    ResilienceTrackerStats,
    RestoreResult,
    RuntimeWasteFilter,
    SystemHealth,
    TokenBucket,
    get_checkpoint_manager,
    get_circuit_breaker,
    get_deduplicator,
    get_resilience_tracker,
    get_runtime_waste_filter,
    get_system_health,
    reset_checkpoint_manager,
    reset_deduplicator,
    reset_resilience_tracker,
    reset_runtime_waste_filter,
    reset_system_health,
)

# Session exports
from core.infrastructure.session import (
    MAX_SESSION_RECORDS,
    AgentAction,
    AnalyticsStats,
    HomeIsolator,
    PhaseMetric,
    RecoveryResult,
    RecoveryStats,
    ScorecardStats,
    SessionAnalytics,
    SessionEfficiencyScorecard,
    SessionMetrics,
    SessionProfile,
    SessionRecord,
    SessionWorkspaceManager,
    SnapshotReason,
    StateRecoveryManager,
    StateSnapshot,
    get_recovery_manager,
    get_session_analytics,
    get_session_scorecard,
    get_workspace_manager,
    reset_recovery_manager,
    reset_session_analytics,
    reset_session_scorecard,
    reset_workspace_manager,
)

__all__ = [
    # Context
    "SessionContext",
    "SessionUserRole",  # Renamed from UserRole to avoid conflict
    "current_session",
    "get_current_session",
    "get_current_session_or_none",
    "has_active_session",
    "use_context",
    "use_context_async",
    "require_context",
    "get_default_context",
    "ensure_context",
    "DEFAULT_TENANT_ID",
    "DEFAULT_USER_ID",
    "DEFAULT_WORKSPACE_ID",
    "ContextAuditTrail",
    "AuditEntry",
    "AuditStats",
    "get_audit_trail",
    "reset_audit_trail",
    # Database
    "PlanTier",
    "TenantStatus",
    "Tenant",
    "User",
    "Workspace",
    "Quota",
    "DEFAULT_QUOTAS",
    "create_quota_for_plan",
    "get_engine",
    "init_db",
    "reset_engine",
    "get_session",
    "create_default_tenant",
    "get_tenant_by_slug",
    "get_tenant_quota",
    "DEFAULT_DB_PATH",
    "QueryPerformanceTracker",
    "QueryRecord",
    "TableProfile",
    "QueryPerformanceStats",
    "get_query_tracker",
    "reset_query_tracker",
    # Bootstrap
    "AutoBootstrap",
    "ProjectAnalysis",
    "SpawnedAgentLoader",
    "SpawnedAgentConfig",
    "discover_and_register_spawned_agents",
    "BootstrapService",
    "SpinoffService",
    "_get_bootstrap_service",
    "_get_spinoff_service",
    "StartupAnalytics",
    "BootStepRecord",
    "ComponentProfile",
    "StartupStats",
    "get_startup_analytics",
    "reset_startup_analytics",
    # Session
    "SessionWorkspaceManager",
    "get_workspace_manager",
    "reset_workspace_manager",
    "HomeIsolator",
    "StateRecoveryManager",
    "StateSnapshot",
    "RecoveryResult",
    "RecoveryStats",
    "SnapshotReason",
    "get_recovery_manager",
    "reset_recovery_manager",
    "SessionAnalytics",
    "PhaseMetric",
    "AgentAction",
    "SessionMetrics",
    "AnalyticsStats",
    "get_session_analytics",
    "reset_session_analytics",
    "SessionRecord",
    "SessionProfile",
    "ScorecardStats",
    "SessionEfficiencyScorecard",
    "get_session_scorecard",
    "reset_session_scorecard",
    "MAX_SESSION_RECORDS",
    # Resilience
    "CircuitBreaker",
    "CircuitState",
    "CircuitOpenError",
    "get_circuit_breaker",
    "SystemHealth",
    "HealthStatus",
    "ComponentHealth",
    "HealthReport",
    "get_system_health",
    "reset_system_health",
    "RateLimiter",
    "ProviderLimits",
    "TokenBucket",
    "CheckpointManager",
    "Checkpoint",
    "CheckpointInfo",
    "RestoreResult",
    "get_checkpoint_manager",
    "reset_checkpoint_manager",
    "RequestDeduplicator",
    "DeduplicationEntry",
    "CheckResult",
    "DeduplicationStats",
    "get_deduplicator",
    "reset_deduplicator",
    "ResilienceEventTracker",
    "ResilienceEvent",
    "EventTypeMetrics",
    "ResilienceTrackerStats",
    "get_resilience_tracker",
    "reset_resilience_tracker",
    "RuntimeWasteFilter",
    "ExchangeRecord",
    "Intervention",
    "InterventionType",
    "InterventionAction",
    "FilterStats",
    "get_runtime_waste_filter",
    "reset_runtime_waste_filter",
]

__version__ = "12.4.0"
